---
platform: linux
inputs:
- name: git-repo
- name: dataflow-git-repo
- name: skipper-git-repo
caches:
- path: maven
- path: gradle
run:
  path: bash
  args:
    - -exc
    - |
      ${PWD}/git-repo/${BASE_PATH}/ci/scripts/check-custom-builds.sh
