---
platform: linux
inputs:
- name: git-repo
outputs:
- name: distribution-repository
caches:
- path: maven
- path: gradle
run:
  path: bash
  args:
    - -exc
    - |
      source /docker-lib.sh
      start_docker
      ${PWD}/git-repo/${BASE_PATH}/ci/scripts/build-project.sh
params:
  ARTIFACTORY_USERNAME: ((artifactory-username))
  ARTIFACTORY_PASSWORD: ((artifactory-password))
  CF_API_USERNAME: ((cf-needles-username))
  CF_API_PASSWORD: ((cf-needles-password))
