resources:
- name: git-repo
  type: git
  source:
    uri: ((github-repo))
    branch: ((branch))

- name: ci-images-git-repo
  type: git
  source:
    uri: ((github-repo))
    branch: ((branch))
    paths: ["((base-path))ci/images/*"]

- name: spring-cloud-dataflow-ci-image
  type: docker-image
  source:
    repository: springsource-docker-private-local.jfrog.io/spring-cloud-dataflow-ci-image
    username: ((artifactory-username))
    password: ((artifactory-password))
    tag: ((branch))

- name: acceptance-tests-reports
  type: s3
  source:
    bucket: ((spr-artifacts-s3-bucket-name))
    regexp: spring-cloud-dataflow-acceptance-tests/spring-cloud-dataflow-acceptance-tests-(.*).tar.gz
    access_key_id: ((spr-s3-access-key-id))
    secret_access_key: ((spr-s3-secret-access-key))
    region_name: us-west-1

jobs:
- name: spring-cloud-dataflow-ci-images
  plan:
  - get: ci-images-git-repo
    trigger: true
  - put: spring-cloud-dataflow-ci-image
    params:
      build: ci-images-git-repo/((base-path))/ci/images/spring-cloud-dataflow-ci-image
      build_args:
        BRANCH: ((branch))
        GITHUB_REPO_RAW: ((github-repo-raw))
        BASE_PATH: ((base-path))

- name: cf-huron-scdf16x-classic
  serial: true
  serial_groups: [cf-env]
  public: false
  plan:
  - get: spring-cloud-dataflow-ci-image
    trigger: true
    passed:
      - "spring-cloud-dataflow-ci-images"
  - get: git-repo
    trigger: true
  - do:
    - task: build-project
      privileged: true
      timeout: 90m
      image: spring-cloud-dataflow-ci-image
      file: git-repo/((base-path))/ci/tasks/build-project.yml
      params:
        BASE_PATH: ((base-path))
        SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_ORG: bamboo
        SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SPACE: test
        SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SKIP_SSL_VALIDATION: true
        SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_SERVICES: rabbit
        SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_TASK_SERVICES: mysql
        MYSQL_SERVICE_NAME: p-mysql
        MYSQL_PLAN_NAME: 100mb
        RABBIT_SERVICE_NAME: p-rabbitmq
        RABBIT_PLAN_NAME: standard
        REDIS_SERVICE_NAME: p-redis
        REDIS_PLAN_NAME: shared-vm
        DEPLOY_PAUSE_TIME: 10
        CF_DIAL_TIMEOUT: 600
        JAVA_BUILDPACK: java_buildpack_offline
        DATAFLOW_VERSION: 1.6.1.BUILD-SNAPSHOT
        SKIPPER_VERSION: 1.0.8.BUILD-SNAPSHOT
        PLATFORM: cloudfoundry
        BINDER: rabbit
        PRE_CLEAN_SCRIPT: "./run.sh -p ${PLATFORM} -t -s -d -dv ${DATAFLOW_VERSION} -sv ${SKIPPER_VERSION}"
        RUN_SCRIPT: "./run.sh -p ${PLATFORM} -b ${BINDER} -dv ${DATAFLOW_VERSION} -c"
        POST_CLEAN_SCRIPT: "./run.sh -p ${PLATFORM} -t -s -d"
      ensure:
        aggregate:
        - put: acceptance-tests-reports
          params:
            file: distribution-repository/spring-cloud-dataflow-acceptance-tests-*.tar.gz

- name: cf-huron-scdf16x-skipper
  serial: true
  serial_groups: [cf-env]
  public: false
  plan:
  - get: spring-cloud-dataflow-ci-image
    trigger: true
    passed:
      - "spring-cloud-dataflow-ci-images"
  - get: git-repo
    trigger: true
  - do:
    - task: build-project
      privileged: true
      timeout: 90m
      image: spring-cloud-dataflow-ci-image
      file: git-repo/((base-path))/ci/tasks/build-project.yml
      params:
        BASE_PATH: ((base-path))
        SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_ORG: bamboo
        SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SPACE: test
        SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SKIP_SSL_VALIDATION: true
        SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_SERVICES: rabbit
        SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_TASK_SERVICES: mysql
        MYSQL_SERVICE_NAME: p-mysql
        MYSQL_PLAN_NAME: 100mb
        RABBIT_SERVICE_NAME: p-rabbitmq
        RABBIT_PLAN_NAME: standard
        REDIS_SERVICE_NAME: p-redis
        REDIS_PLAN_NAME: shared-vm
        DEPLOY_PAUSE_TIME: 10
        CF_DIAL_TIMEOUT: 600
        JAVA_BUILDPACK: java_buildpack_offline
        DATAFLOW_VERSION: 1.6.1.BUILD-SNAPSHOT
        SKIPPER_VERSION: 1.0.8.BUILD-SNAPSHOT
        PLATFORM: cloudfoundry
        BINDER: rabbit
        PRE_CLEAN_SCRIPT: "./run.sh -p ${PLATFORM} -t -s -d -dv ${DATAFLOW_VERSION} -sv ${SKIPPER_VERSION}"
        RUN_SCRIPT: "./run.sh -p ${PLATFORM} -b ${BINDER} -dv ${DATAFLOW_VERSION} -sv ${SKIPPER_VERSION} -c"
        POST_CLEAN_SCRIPT: "./run.sh -p ${PLATFORM} -t -s -d"
      ensure:
        aggregate:
        - put: acceptance-tests-reports
          params:
            file: distribution-repository/spring-cloud-dataflow-acceptance-tests-*.tar.gz

- name: local-scdf171-bs-skipper-111-bs-rabbit
  serial: true
  public: false
  plan:
  - get: spring-cloud-dataflow-ci-image
    trigger: true
    passed:
      - "spring-cloud-dataflow-ci-images"
  - get: git-repo
    trigger: true
  - do:
    - task: build-project
      privileged: true
      timeout: 90m
      image: spring-cloud-dataflow-ci-image
      file: git-repo/((base-path))/ci/tasks/build-project.yml
      params:
        BASE_PATH: ((base-path))
        DATAFLOW_VERSION: 1.7.1.BUILD-SNAPSHOT
        SKIPPER_VERSION: 1.1.1.BUILD-SNAPSHOT
        PLATFORM: local
        BINDER: rabbit
        RUN_SCRIPT: "./run.sh -p ${PLATFORM} -b ${BINDER} -m -dv ${DATAFLOW_VERSION} -sv ${SKIPPER_VERSION} -c"
      ensure:
        aggregate:
        - put: acceptance-tests-reports
          params:
            file: distribution-repository/spring-cloud-dataflow-acceptance-tests-*.tar.gz

